crates/jxl-frame/src/data/lf_global.rs
crates/jxl-frame/src/data/mod.rs
crates/jxl-frame/src/data/spline.rs
crates/jxl-frame/src/error.rs
crates/jxl-render/src/blend.rs
crates/jxl-render/src/lib.rs

Spline decoding and rendering.
`Splines` are decoded as vector of `QuantSpline` -- splines with quantized DCT coefficients, and delta encoded control point coordinates.
`QuantSpline` can be decoded to `Spline` using `QuantSpline::dequant` (probably, at the rendering stage, as it requires base_correlation for X and B from `LfChannelCorrelation`)
`Spline::fmt` formatting is done in  jxl_from_tree syntax

Add splines decoding and rendering

---

crates/jxl-oxide-cli/src/bin/jxl-dec.rs

Currently, when we converting float to uint, we do `floor`, not `round`, this results in a different rendering of VarDCT images than libjxl.

jxl-oxide-cli: Fix float rounding for VarDCT

---

crates/jxl-color/src/tf.rs

As in [libjxl's `Fallback for scalar`](https://github.com/libjxl/libjxl/blob/11f7d4a056ec7ea3da92931ad28f5bb45f1f5d7d/lib/jxl/transfer_functions-inl.h#LL398C1-L398C1)
Fixes #26

jxl-color: Fix `linear_to_srgb` panic

---

crates/jxl-coding/src/ans.rs

Fixes
```sh
Thread 'main' panicked at 'index out of bounds: the len is 32 but the index is 32',
crates/jxl-coding/src/ans.rs:92:21
```

jxl-coding: Fix ANS unused zeroing

---

crates/jxl-oxide/tests/decode.rs
crates/jxl-render/src/cut_grid.rs
crates/jxl-render/src/inner.rs

Fixes #32
Fixes the size of framebuffer being smaller than required.

jxl-render: Fix framebuffer size rounding for chroma subsampled images

---

crates/jxl-frame/src/data/toc.rs

Prevent OOM on invalid images with enormous amount of toc_entries
https://github.com/libjxl/libjxl/blob/c2e546a17fa579748edae2667ebb04e1a9a61783/lib/jxl/toc.cc#L25-L30

jxl-frame: TOC entry count limit

---

crates/jxl-oxide/src/lib.rs
crates/jxl-oxide/tests/conformance.rs
crates/jxl-render/src/lib.rs

Adds rendering of spot color channels by default, a `set_render_spot_colour` method to enable/disable their rendering  and a `render_spot_colour` method to get the value of that flag in `JxlRenderer`
Rendering of spot channels onto color channels is disabled during conformance testing since they are tested as separate channels
fixes https://github.com/tirr-c/jxl-oxide/issues/15
| before: | after: |
| - | - |
|![before](https://github.com/tirr-c/jxl-oxide/assets/69643766/7bb4f3d2-14ba-45c3-8329-10bd9f065e49)| ![after](https://github.com/tirr-c/jxl-oxide/assets/69643766/ae546ae9-518e-4a8c-a7d2-fd89244c32c2)|

Add spot colour channel rendering

---

crates/jxl-oxide-cli/src/bin/jxl-dec.rs

ICC profiles are used instead of sRGB chunks.

jxl-dec: Do not emit sRGB chunks

---

crates/jxl-frame/src/data/lf_global.rs

Fixes #65 
JXL specification had a bug in MA tree node limits.

jxl-frame: Fix global MA tree node limit to match libjxl

---

crates/jxl-oxide-cli/src/bin/jxl-dec.rs

This PR adds `OutputFormat::Npy`, mainly used for conformance testing.

jxl-dec: Add support for Numpy buffer output

---

crates/jxl-frame/src/data/lf_global.rs
crates/jxl-frame/src/data/pass_group.rs
crates/jxl-frame/src/data/toc.rs
crates/jxl-frame/src/lib.rs
crates/jxl-modular/src/image.rs
crates/jxl-modular/src/lib.rs
crates/jxl-modular/src/transform.rs
crates/jxl-oxide/src/lib.rs
crates/jxl-render/src/blend.rs
crates/jxl-render/src/cut_grid.rs
crates/jxl-render/src/dct.rs
crates/jxl-render/src/dct/generic.rs
crates/jxl-render/src/dct/x86_64/mod.rs
crates/jxl-render/src/inner.rs
crates/jxl-render/src/lib.rs
crates/jxl-render/src/vardct/generic.rs
crates/jxl-render/src/vardct/mod.rs
crates/jxl-render/src/vardct/transform.rs
crates/jxl-render/src/vardct/x86_64.rs
crates/jxl-vardct/src/dct_select.rs
crates/jxl-vardct/src/hf_coeff.rs

Make frame decoding lazy.
- Groups are decoded only when needed during rendering.
- Image header is shared using `Arc`. This simplifies API by removing a lifetime parameter.
- There is no `PassGroup` struct anymore; Modular data and HF coefficients are decoded directly into the buffer.
- Removed various heap allocations.

Rewrite frame decoding

---

crates/jxl-oxide-cli/src/bin/jxl-dec.rs
crates/jxl-oxide-cli/src/bin/jxl-info.rs
crates/jxl-oxide/src/bin/generate-fixture.rs
crates/jxl-oxide/src/lib.rs
crates/jxl-oxide/tests/conformance.rs
crates/jxl-oxide/tests/decode.rs

Now users don't need to deal with lifetime parameters since `JxlRenderer` doesn't exist anymore. All the methods of `JxlRenderer` is merged into `JxlImage`.
This change was possible because single `RenderContext` can be reused for multiple renders of an image, due to recent patches to `jxl-render`.

jxl-oxide: Merge JxlRenderer into JxlImage

---

crates/jxl-image/src/lib.rs
crates/jxl-oxide-cli/src/bin/jxl-dec.rs
crates/jxl-oxide-cli/src/bin/jxl-info.rs
crates/jxl-oxide/src/lib.rs

Fixes #63.
```console
$ jxl-info sunset_logo.jxl
JPEG XL image
Image dimension: 924x1386
Encoded image dimension: 1386x924
Orientation of encoded image: rotated 90 degrees CCW, and then flipped horizontally
Bit depth: 10 bits
Color encoding:
Colorspace: RGB
White point: D65
Primaries: sRGB
Transfer function: sRGB
(... snip ...)
```

jxl-oxide-cli: Apply orientation to reported image dimension

---

crates/jxl-oxide/src/lib.rs

`rendered_icc` should be used in most cases.

jxl-oxide: Add note to `embedded_icc`

---

Cargo.lock
README.md
crates/jxl-frame/Cargo.toml
crates/jxl-image/Cargo.toml
crates/jxl-modular/Cargo.toml
crates/jxl-oxide-cli/Cargo.toml
crates/jxl-oxide/Cargo.toml
crates/jxl-render/Cargo.toml
crates/jxl-vardct/Cargo.toml

Updated crates:
- `jxl-image` 0.5.0
- `jxl-modular` 0.3.0
- `jxl-vardct` 0.3.0
- `jxl-frame` 0.5.0
- `jxl-render` 0.4.0
- `jxl-oxide` 0.4.0
- `jxl-oxide-cli` 0.2.3
- CLI is backwards compatible

jxl-oxide v0.4.0

---

crates/jxl-grid/src/simd.rs
crates/jxl-render/src/filter/epf.rs
crates/jxl-render/src/filter/generic.rs
crates/jxl-render/src/filter/mod.rs
crates/jxl-render/src/filter/x86_64.rs

cc #80 
Conformance test `bike` has 3-step EPF and decoding it is now ~2.3x faster.

jxl-render: SSE2 version of EPF

---

crates/jxl-render/src/filter/epf.rs
crates/jxl-render/src/filter/impls/generic.rs
crates/jxl-render/src/filter/impls/x86_64/epf_avx2.rs
crates/jxl-render/src/filter/impls/x86_64/epf_sse2.rs

cc #80 
Adjusts mirror padding so that the grid width becomes multiple of 8. Also fixes mirror operation with grid width less than 3.

jxl-render: Improve EPF performance

---

crates/jxl-grid/src/simd.rs
crates/jxl-render/src/filter/impls.rs
crates/jxl-render/src/filter/impls/aarch64.rs
crates/jxl-render/src/filter/impls/aarch64/epf.rs
crates/jxl-render/src/filter/impls/generic.rs

On my M1 Max machine, decoding performance of jxl-oxide is on par with single-threaded libjxl, and it's even faster than libjxl for some images.

jxl-render: NEON version of EPF

---

crates/jxl-bitstream/src/reader.rs
crates/jxl-frame/src/data/toc.rs
crates/jxl-frame/src/lib.rs
crates/jxl-oxide-cli/src/bin/jxl-info.rs
crates/jxl-oxide/src/lib.rs
crates/jxl-render/src/lib.rs

Use `--with-offset` to print frame offset and group size information:
<details>
```
JPEG XL image (BareCodestream)
Image dimension: 800x600
Bit depth: 8 bits
XYB encoded, suggested display color encoding:
Colorspace: RGB
White point: D65
Primaries: sRGB
Transfer function: sRGB
Frame #0 (keyframe)
VarDCT (lossy)
Frame type: Regular
800x600; (0, 0)
Offset (in codestream): 9 (0x9)
Frame header size: 31 (0x1f) bytes
Group sizes, in bitstream order:
LfGlobal: 11168 (0x2ba0) bytes
LfGroup(0): 8525 (0x214d) bytes
HfGlobal: 868 (0x364) bytes
GroupPass { pass_idx: 0, group_idx: 0 }: 3889 (0xf31) bytes
GroupPass { pass_idx: 0, group_idx: 1 }: 8053 (0x1f75) bytes
GroupPass { pass_idx: 0, group_idx: 2 }: 4086 (0xff6) bytes
GroupPass { pass_idx: 0, group_idx: 3 }: 13 (0xd) bytes
GroupPass { pass_idx: …
```

jxl-info: Print offsets of frame groups

---

crates/jxl-bitstream/LICENSE-APACHE
crates/jxl-bitstream/LICENSE-MIT
crates/jxl-coding/LICENSE-APACHE
crates/jxl-coding/LICENSE-MIT
crates/jxl-color/LICENSE-APACHE
crates/jxl-color/LICENSE-MIT
crates/jxl-frame/LICENSE-APACHE
crates/jxl-frame/LICENSE-MIT
crates/jxl-grid/LICENSE-APACHE
crates/jxl-grid/LICENSE-MIT
crates/jxl-image/LICENSE-APACHE
crates/jxl-image/LICENSE-MIT
crates/jxl-modular/LICENSE-APACHE
crates/jxl-modular/LICENSE-MIT
crates/jxl-oxide-cli/LICENSE-APACHE
crates/jxl-oxide-cli/LICENSE-MIT
crates/jxl-oxide-fuzz/LICENSE-APACHE
crates/jxl-oxide-fuzz/LICENSE-MIT
crates/jxl-oxide/LICENSE-APACHE
crates/jxl-oxide/LICENSE-MIT
crates/jxl-render/LICENSE-APACHE
crates/jxl-render/LICENSE-MIT
crates/jxl-vardct/LICENSE-APACHE
crates/jxl-vardct/LICENSE-MIT

This ensures that the license files get included in individual crates that are uploaded to crates.io.

Add license symlinks to individual crates

---

crates/jxl-render/src/filter/epf.rs
crates/jxl-render/src/filter/impls/aarch64.rs
crates/jxl-render/src/filter/impls/aarch64/epf.rs
crates/jxl-render/src/filter/impls/generic.rs
crates/jxl-render/src/filter/impls/x86_64.rs
crates/jxl-render/src/filter/impls/x86_64/epf_avx2.rs
crates/jxl-render/src/filter/impls/x86_64/epf_sse2.rs

Reuse the output buffer to reduce allocation. Also improves EPF performance.

jxl-render: Reduce EPF buffer allocation

---

crates/jxl-color/src/convert.rs
crates/jxl-color/src/convert/tone_map.rs
crates/jxl-color/src/gamut.rs
crates/jxl-color/src/lib.rs
crates/jxl-color/src/tf.rs
crates/jxl-color/src/tf/rec2408.rs
crates/jxl-oxide-cli/src/bin/jxl-dec.rs
crates/jxl-render/src/inner.rs
crates/jxl-render/src/lib.rs

Resolves #9 
This PR implements:
- Rec.2408 tone mapper with peak detection, YRGB method (which is used by libjxl)
- Gamut mapper, ported from libjxl

jxl-color: Implement tone mapping

---

crates/jxl-oxide/fuzz/.gitignore
crates/jxl-oxide/fuzz/Cargo.toml
crates/jxl-oxide/fuzz/fuzz_targets/decode.rs

Used to discover #163, #164,  #165,  #169,  #170
Heavily based on the honggfuzz target that is already in the repo.
Works best when seeded with valid JPEG XL files with various encoding parameters, rather than starting from scratch. This is my seed corpus: [jxl_fuzzing_seeds.tar.gz](https://github.com/tirr-c/jxl-oxide/files/13852139/jxl_fuzzing_seeds.tar.gz)
I am contributing it along with the seed corpus so that you are no longer dependent on me running it.

Add an initial fuzzing harness using cargo-fuzz

---

crates/jxl-frame/src/data/lf_global.rs
crates/jxl-modular/src/image.rs
crates/jxl-modular/src/lib.rs
crates/jxl-modular/src/ma.rs

Fixes #170 
- Detects a simple infinite MA tree case. I guess this check is the same as [one in libjxl][dec_ma.cc].
- MA tree allocation is tracked.
[dec_ma.cc]: https://github.com/libjxl/libjxl/blob/875e72dd1e3e2d71835aa2490f595a7d5968199e/lib/jxl/modular/encoding/dec_ma.cc#L96-L97

jxl-modular: Handle large MA trees

---

crates/jxl-oxide/Cargo.toml

jxl-oxide: Remove lcms2 requirement from conformance test

---

crates/jxl-coding/src/lib.rs

This greatly improves fast-lossless case.

jxl-coding: Do not preallocate LZ77 window

---

Cargo.lock
crates/jxl-oxide-cli/Cargo.toml

Fixes panic on subcommand-arg conflict.

jxl-oxide-cli: Update clap to 4.4.18

---

crates/jxl-bitstream/src/memory.rs
crates/jxl-coding/src/ans.rs
crates/jxl-render/src/vardct/mod.rs
crates/jxl-vardct/src/hf_coeff.rs

Avoid int-float conversion and float addition during HF coefficient decoding.

Various optimizations around HF coeff decoding

---

crates/jxl-modular/src/image.rs
crates/jxl-modular/src/ma.rs
crates/jxl-modular/src/predictor.rs
crates/jxl-modular/src/sample.rs
crates/jxl-modular/src/transform.rs

<details>
<summary>Benchmark result (x86_64)</summary>
```
lumine-paimon.d0-e7/preferred-color
time:   [102.55 ms 103.09 ms 103.67 ms]
thrpt:  [17.127 Melem/s 17.224 Melem/s 17.315 Melem/s]
change:
time:   [-2.3218% -1.5582% -0.7626%] (p = 0.00 < 0.05)
thrpt:  [+0.7684% +1.5829% +2.3770%]
Change within noise threshold.
Found 6 outliers among 100 measurements (6.00%)
3 (3.00%) high mild
3 (3.00%) high severe
minecraft.d0-e6/preferred-color
time:   [89.826 ms 90.212 ms 90.599 ms]
thrpt:  [40.689 Melem/s 40.864 Melem/s 41.039 Melem/s]
change:
time:   [-7.9255% -7.3408% -6.7342%] (p = 0.00 < 0.05)
thrpt:  [+7.2205% +7.9224% +8.6077%]
Performance has improved.
srgb.d0-e1/preferred-color
time:   [12.066 ms 12.103 ms 12.144 ms]
thrpt:  [118.28 Melem/s 118.68 Melem/s 119.04 Melem/s]
change:
time: …
```

jxl-modular: Try various optimizations

---

crates/jxl-color/src/cms.rs
crates/jxl-color/src/convert.rs
crates/jxl-color/src/convert/tone_map.rs
crates/jxl-render/src/lib.rs

This might help qcms implementation.

jxl-color: Make peak detection non-default, add an option to pass sRGB samples to CMS

---

CHANGELOG.md
crates/jxl-modular/src/image.rs

This is more like a bug in libjxl, but it's not really possible to "fix" libjxl at this point.
Fixes #268

jxl-modular: Include meta channels when computing dist_multiplier

---

crates/jxl-modular/src/image.rs

Try to mitigate libjxl/libjxl#3356.

jxl-modular: Detect LZ77 bug case

---

.github/workflows/build.yml
crates/jxl-oxide-wasm/README.md
crates/jxl-oxide-wasm/update-package-json.mjs

Include only simd128 builds, enable WeakRef and reference types in bindings.

jxl-oxide-wasm: Update packaging

---

crates/jxl-oxide-cli/Cargo.toml
crates/jxl-oxide-cli/src/main.rs

Add a feature `mimalloc`, enabled by default.

jxl-oxide-cli: Move mimalloc into a feature flag

---

crates/jxl-frame/src/data/pass_group.rs
crates/jxl-grid/src/simple_grid.rs
crates/jxl-grid/src/subgrid.rs
crates/jxl-render/src/modular.rs
crates/jxl-render/src/util.rs
crates/jxl-render/src/vardct/mod.rs
crates/jxl-vardct/src/hf_coeff.rs

Benchmark:
- Baseline: `main` (f17d6b4)
- Ryzen 5600X, Arch Linux on Hyper-V VM
- mimalloc is used for both measurements
<details>
<summary>Benchmark result</summary>
```
nahida-motion.d1-e7/preferred-color
time:   [49.241 ms 49.445 ms 49.698 ms]
thrpt:  [74.176 Melem/s 74.555 Melem/s 74.864 Melem/s]
change:
time:   [-8.7105% -8.0220% -7.2916%] (p = 0.00 < 0.05)
thrpt:  [+7.8651% +8.7216% +9.5416%]
Performance has improved.
Found 5 outliers among 100 measurements (5.00%)
4 (4.00%) high mild
1 (1.00%) high severe
starrail.d1-e6/preferred-color
time:   [49.373 ms 49.515 ms 49.664 ms]
thrpt:  [74.227 Melem/s 74.451 Melem/s 74.664 Melem/s]
change:
time:   [-7.7917% -7.2560% -6.7493%] (p = 0.00 < 0.05)
thrpt:  [+7.2378% +7.8237% +8.4501%]
Performance has improved.
Found 7 outliers among 100 …
```

jxl-render: Load VarDCT passes in parallel

---

crates/jxl-grid/src/simple_grid.rs
crates/jxl-render/src/blend.rs
crates/jxl-render/src/image.rs

Avoid allocating zero-filled memory region when possible.

jxl-render: Reduce zerofilling memory

---

crates/jxl-render/src/blend.rs
crates/jxl-render/src/features/noise.rs
crates/jxl-render/src/features/upsampling.rs
crates/jxl-render/src/image.rs
crates/jxl-render/src/modular.rs
crates/jxl-render/src/render.rs
crates/jxl-render/src/util.rs
crates/jxl-render/src/vardct/mod.rs
crates/jxl-vardct/src/dequant.rs

- Refactor non-separable upsampling.
- Move upsampling stage after rendering features.
- Upsample extra channels to match color channels first, when patches are used.
- Remove unused trace log in jxl-vardct.

jxl-render: Separate extra channel upsampling stage when patches are used

---

CHANGELOG.md
crates/jxl-color/src/convert.rs
crates/jxl-oxide-cli/src/decode.rs
crates/jxl-oxide-wasm/src/lib.rs
crates/jxl-oxide/src/fb.rs
crates/jxl-oxide/src/lib.rs
crates/jxl-oxide/tests/conformance.rs
crates/jxl-render/src/blend.rs
crates/jxl-render/src/image.rs
crates/jxl-render/src/lib.rs
crates/jxl-render/src/render.rs
crates/jxl-render/src/state.rs

Less buffer copies

---

crates/jxl-oxide-cli/src/commands.rs
crates/jxl-oxide-cli/src/commands/progressive.rs
crates/jxl-oxide-cli/src/decode.rs
crates/jxl-oxide-cli/src/lib.rs
crates/jxl-oxide-cli/src/main.rs
crates/jxl-oxide-cli/src/output.rs
crates/jxl-oxide-cli/src/progressive.rs

Add a new devtool subcommand `progressive`, which can be used to test partial decoding and progressive rendering.
Usage example:
```
jxl-oxide progressive input.jxl --step 1024 -o path/to/output/dir/
```

jxl-oxide-cli: Add devtool subcommand `progressive`

---

crates/jxl-oxide/Cargo.toml
crates/jxl-oxide/src/lib.rs

Right now the `image` feature in `jxl-oxide` crate is disabled on docs.rs. Because of that the docs on the integration do not show up on docs.rs at all. This PR fixes that.
`doc_auto_cfg` is a [nightly rustdoc feature](https://doc.rust-lang.org/rustdoc/unstable-features.html), so it's only enabled for docs.rs to make it possible to build the docs for this crate on stable. All ways of documenting conditional features are currently nightly-only, but are also widely used so they're unlikely to outright break.
You can preview the generated documentation with this command: `cargo +nightly rustdoc --open --features=image -- --cfg=docsrs`
It looks like this:

Document `image` crate integration on docs.rs

---

Cargo.lock
crates/jxl-bitstream/src/container.rs
crates/jxl-bitstream/src/container/box_header.rs
crates/jxl-bitstream/src/container/parse.rs
crates/jxl-oxide-cli/src/info.rs
crates/jxl-oxide/Cargo.toml
crates/jxl-oxide/examples/image-integration.rs
crates/jxl-oxide/src/aux_box.rs
crates/jxl-oxide/src/aux_box/exif.rs
crates/jxl-oxide/src/integration/image.rs
crates/jxl-oxide/src/lib.rs

Added `brotli-decompressor` as a dependency of `jxl-oxide`.
Resolves #381

Extract (potentially Brotli-compressed) Exif metadata

---

CHANGELOG.md
crates/jxl-oxide-cli/src/commands/decode.rs
crates/jxl-oxide-cli/src/commands/progressive.rs
crates/jxl-oxide-cli/src/commands/slow_motion.rs
crates/jxl-oxide-cli/src/decode.rs
crates/jxl-oxide-cli/src/lib.rs
crates/jxl-oxide-cli/src/progressive.rs
crates/jxl-oxide-cli/src/slow_motion.rs
crates/jxl-oxide-tests/benches/decode.rs
crates/jxl-oxide/src/lib.rs
crates/jxl-threadpool/src/lib.rs

Add an option to use global Rayon thread pool.
Using multiple thread pools simultaneously seems to cause stack overflow in some cases: https://github.com/rayon-rs/rayon/issues/751. `JxlThreadPool::rayon_global` helps working around the issue by using single global thread pool.

jxl-threadpool: Add `rayon_global`

---

crates/jxl-oxide-wasm/src/lib.rs

Thanks for making this library! I've been using it for my [VS Code extension](https://github.com/printfn/jpeg-xl-vscode).
I noticed that `jxl-oxide-wasm` doesn't expose the width and height of the image, so I thought it'd be nice if it was more easily available since I'm currently having to manually parse the PNG header to extract this info.

Add image dimensions to jxl-oxide-wasm

---

Cargo.lock
crates/jxl-oxide-cli/Cargo.toml
crates/jxl-oxide-cli/src/commands.rs
crates/jxl-oxide-cli/src/main.rs

- Output logs to stderr.
- Add `--color` option.

jxl-oxide-cli: Better terminal handling

---

Cargo.lock
Cargo.toml
crates/jxl-bitstream/Cargo.toml
crates/jxl-coding/Cargo.toml
crates/jxl-color/Cargo.toml
crates/jxl-frame/Cargo.toml
crates/jxl-grid/Cargo.toml
crates/jxl-image/Cargo.toml
crates/jxl-jbr/Cargo.toml
crates/jxl-modular/Cargo.toml
crates/jxl-oxide-common/Cargo.toml
crates/jxl-oxide/Cargo.toml
crates/jxl-render/Cargo.toml
crates/jxl-threadpool/Cargo.toml
crates/jxl-vardct/Cargo.toml
fuzz/Cargo.lock

Not stabilizing jxl-grid because I'm not very sure about its current API surface.

Stabilize jxl-bitstream, jxl-oxide-common, jxl-coding, jxl-threadpool

---

crates/jxl-grid/src/lib.rs
crates/jxl-grid/src/mutable_subgrid.rs
crates/jxl-grid/src/shared_subgrid.rs
crates/jxl-grid/src/test/mod.rs
crates/jxl-grid/src/test/subgrids.rs

Replaces #467, resolves #464
Fixes splitting methods of `SharedSubgrid` to match `MutableSubgrid`.

jxl-grid: Fix splitting of `SharedSubgrid`, add tests

---

crates/jxl-oxide-tests/tests/image/mod.rs
crates/jxl-oxide/src/integration/image.rs

Fix `image` crate integration failing to load image with reference frame

---

crates/jxl-coding/src/lib.rs

Decoder cannot fill Modular buffers statelessly when LZ77 is enabled, because LZ77 is stateful (e.g. leftover LZ77 copies, decoded symbol window).

jxl-coding: Disable single token fast path if LZ77 is enabled
