tirr-c/jxl-oxide

crates/jxl-frame/src/data/spline.rs, crates/jxl-render/src/lib.rs
Fix estimated_area calculation and uncomment `TooLargeEstimatedArea` error
see also: https://github.com/libjxl/libjxl/commit/7d559dd827493f0c0790e8ddc1ca1d39fc985dfc
=> splines: Fix estimated_area calculation

crates/jxl-frame/src/data/spline.rs, crates/jxl-render/src/blend.rs, crates/jxl-render/src/lib.rs
See https://github.com/libjxl/libjxl/pull/2425
=> splines: Update estimated_area calculation

crates/jxl-frame/src/data/noise.rs
Small clean-up and activated dead/unused code lint
=> noise: Enable linting of unused code

crates/jxl-render/src/features/spline.rs
There were redundant equations for `a` and `b`
=> splines: Add comments and fix number of equations

crates/jxl-coding/src/error.rs, crates/jxl-coding/src/lib.rs
Like in https://github.com/libjxl/libjxl/blob/c8a4a7aa88f926c00ca4178f6677f83c2fa4e290/lib/jxl/dec_ans.cc#LL270C11-L270C11
=> jxl-coding: IntegerConfig validation

crates/jxl-frame/src/lib.rs
Check the `alpha_channel` indices of extra channels
as in blend: https://github.com/tirr-c/jxl-oxide/blob/7b13dcf67d8e6a8ee63b129525f1e6df498f6ce2/crates/jxl-render/src/blend.rs#L174-L177
=> jxl-frame: `blending_info.alpha_channel` range check

crates/jxl-vardct/src/hf_metadata.rs
Also log details when validation failed.
cc #25
=> jxl-vardct: Validate BlockInfo

crates/jxl-image/src/lib.rs
=> jxl-image: BitDepth check

crates/jxl-image/src/lib.rs
=> jxl-image: Tone-mapping check

crates/jxl-color/src/icc.rs
https://github.com/libjxl/libjxl/blob/b55725bd5387576d172c92eede6bef3c6003a87b/lib/jxl/icc_codec.cc#L298-L301
=> jxl-color: Limit ICC encoded profile size

crates/jxl-oxide/src/lib.rs
Make the ICC profile of the rendered image accessible without creating `JxlRenderer`.
=> jxl-oxide: Add `JxlImage::rendered_icc`

crates/jxl-bitstream/src/error.rs, crates/jxl-color/src/icc.rs, crates/jxl-frame/src/data/lf_global.rs, crates/jxl-frame/src/data/patch.rs, crates/jxl-frame/src/data/spline.rs, crates/jxl-frame/src/error.rs, crates/jxl-frame/src/lib.rs, crates/jxl-image/src/lib.rs, crates/jxl-modular/src/lib.rs, crates/jxl-modular/src/ma.rs, crates/jxl-render/src/error.rs, crates/jxl-render/src/features/spline.rs
Fixes #47.
- `jxl-frame` has breaking changes: different trait impl for `Patches`
=> Add various limits for Level 10

.github/workflows/ci.yml, codecov.yml
=> Collect code coverage

Cargo.lock, crates/jxl-oxide-cli/Cargo.toml
There was a yanked package, so update dependencies as well.
=> jxl-oxide-cli: v0.2.2

crates/jxl-image/src/lib.rs, crates/jxl-oxide-cli/src/bin/jxl-dec.rs, crates/jxl-oxide/src/lib.rs, crates/jxl-render/src/blend.rs, crates/jxl-render/src/features/noise.rs, crates/jxl-render/src/features/spline.rs, crates/jxl-render/src/features/upsampling.rs, crates/jxl-render/src/filter/epf.rs, crates/jxl-render/src/inner.rs, crates/jxl-render/src/lib.rs, crates/jxl-render/src/region.rs, crates/jxl-render/src/vardct/mod.rs
=> jxl-render: Render with crop regions

crates/jxl-coding/src/ans.rs, crates/jxl-coding/src/lib.rs, crates/jxl-coding/src/prefix.rs, crates/jxl-modular/src/image.rs, crates/jxl-modular/src/ma.rs
Mainly for libjxl fast-lossless (`-e1`) images, which got 2x speedup.
=> Optimize for special modular images

crates/jxl-bitstream/src/lib.rs, crates/jxl-bitstream/src/macros.rs, crates/jxl-coding/src/ans.rs, crates/jxl-coding/src/lib.rs, crates/jxl-coding/src/prefix.rs, crates/jxl-frame/src/data/pass_group.rs, crates/jxl-grid/src/lib.rs, crates/jxl-grid/src/simd.rs, crates/jxl-grid/src/simple_grid.rs, crates/jxl-grid/src/subgrid.rs, crates/jxl-modular/src/image.rs, crates/jxl-modular/src/predictor.rs, crates/jxl-render/src/dct/x86_64/mod.rs, crates/jxl-vardct/src/hf_coeff.rs, crates/jxl-vardct/src/hf_metadata.rs, crates/jxl-vardct/src/hf_pass.rs
This is a mix of various tweaks and refactoring, which actually improves performance a tiny bit.
=> Various optimizations and refactoring

crates/jxl-color/src/fastmath.rs, crates/jxl-color/src/fastmath/powf.rs, crates/jxl-color/src/fastmath/rational_poly.rs, crates/jxl-color/src/lib.rs, crates/jxl-color/src/tf.rs, crates/jxl-color/src/xyb.rs, crates/jxl-color/src/ycbcr.rs, crates/jxl-oxide/tests/crop.rs
Fast math routines are ported from libjxl.
=> jxl-color: Fast color transforms

.github/workflows/ci.yml
Added it to `grcov` step in the coverage job.
=> Collect `crop` test coverage

crates/jxl-oxide/tests/decode.rs
Turns out that various optimization routines introduce errors in sample values among CPU architectures, especially for lossy images.
=> test(decode): Use conformance testing thresholds for decode tests

.github/workflows/ci.yml, Cargo.lock, crates/jxl-oxide/Cargo.toml
=> Run tests on ARM architectures

crates/jxl-grid/src/simple_grid.rs, crates/jxl-image/src/lib.rs, crates/jxl-modular/src/transform.rs, crates/jxl-modular/src/transform/squeeze.rs, crates/jxl-render/src/modular.rs
- Faster unsqueeze in CPU that has AVX2 support.
- Faster Modular integer-to-float conversion.
=> Optimize modular more

Cargo.lock, crates/jxl-modular/src/transform.rs, crates/jxl-render/src/filter/impls/generic.rs, crates/jxl-render/src/lib.rs, crates/jxl-render/src/modular.rs, crates/jxl-render/src/vardct/mod.rs, crates/jxl-threadpool/Cargo.toml, crates/jxl-threadpool/src/lib.rs
Not sure this actually improves performance
=> Use Rayon for thread pool job distribution

Cargo.lock, README.md, crates/jxl-oxide/Cargo.toml
It's here only to update published README.md.
=> jxl-oxide v0.5.1

crates/jxl-oxide-cli/src/bin/jxl-dec.rs
- Custom chromaticity syntax is removed.
- D50 (0.345669, 0.358496) is added to the list of white points.
=> jxl-oxide-cli: Change --target-colorspace syntax, add D50 to white point

crates/jxl-color/src/icc/decode.rs
=> jxl-color: Perform quick ICC validity check before fully reading stream

crates/jxl-frame/src/header.rs
Seems like a spec bug; following libjxl way as it makes sense.
=> jxl-frame: Fix BlendingInfo decoding

crates/jxl-coding/src/lib.rs, crates/jxl-coding/src/prefix.rs
libjxl doesn't report error in hybrid integer decoding, since if it's invalid there, it would be caught during decoding process afterwards. This PR follows that approach and reduces branches.
=> jxl-coding: Optimize entropy coding more

Cargo.lock, crates/jxl-oxide/Cargo.toml, crates/jxl-oxide/benches/decode.rs
Uses [criterion.rs] for benchmarking.
[criterion.rs]: https://github.com/bheisler/criterion.rs
=> jxl-oxide: Add benchmark harness

crates/jxl-coding/src/ans.rs, crates/jxl-coding/src/lib.rs, crates/jxl-coding/src/prefix.rs, crates/jxl-vardct/src/hf_coeff.rs, crates/jxl-vardct/src/hf_pass.rs
A little bit faster in general.
=> Try more optimizations

crates/jxl-oxide/benches/decode.rs
Add images with different number of EPF steps.
=> jxl-oxide: Add more benchmark

crates/jxl-render/src/vardct/mod.rs
The bug is triggered only with non-8x8 varblocks in chroma subsampled image.
Maybe this does not happen on any JXL image currently exists, but this is a bug anyway.
=> jxl-render: Fix chroma subsampled varblock alignment test

crates/jxl-color/src/icc/decode.rs, crates/jxl-frame/src/data/spline.rs
=> Add missing ANS validation

crates/jxl-oxide/tests/conformance.rs
The spec says that peak/mean error is checked per channel. For example, `alpha_premultiplied` has VarDCT color channels with filters and a 16-bit Modular alpha channel without any filters. We need different peak/mean error information to those channels because different thresholds apply to each channel type.
=> jxl-oxide (conformance): Specify expected max error per channel

crates/jxl-bitstream/src/lib.rs, crates/jxl-bitstream/src/memory.rs, crates/jxl-modular/src/image.rs, crates/jxl-oxide-cli/src/commands/decode.rs, crates/jxl-oxide/src/lib.rs
It's likely that the spec will be changed to match libjxl.
cc libjxl/libjxl#3356
=> Rename Lz77Mode variants, make IncludeMeta the default

crates/jxl-oxide/tests/crop.rs, crates/jxl-render/src/util.rs
=> jxl-render: Fix crash during cropped decoding

crates/jxl-modular/src/image.rs, crates/jxl-modular/src/ma.rs
Specialized routine for libjxl e2.
=> jxl-modular: Specialized decode routine for gradient-only lookup table

CHANGELOG.md, crates/jxl-modular/src/transform/palette.rs, crates/jxl-oxide/tests/decode.rs
=> Fix incorrect colors with complex inverse palette

CHANGELOG.md, crates/jxl-modular/src/transform.rs, crates/jxl-oxide/tests/decode.rs
=> backport: Fix incorrect colors with complex inverse palette

CHANGELOG.md, Cargo.lock, crates/jxl-bitstream/Cargo.toml, crates/jxl-coding/Cargo.toml, crates/jxl-color/Cargo.toml, crates/jxl-frame/Cargo.toml, crates/jxl-grid/Cargo.toml, crates/jxl-image/Cargo.toml, crates/jxl-modular/Cargo.toml, crates/jxl-oxide-cli/Cargo.toml, crates/jxl-oxide-wasm/Cargo.toml, crates/jxl-oxide/Cargo.toml, crates/jxl-render/Cargo.toml, crates/jxl-vardct/Cargo.toml, fuzz/Cargo.lock
=> Bump version

crates/jxl-render/src/image.rs, crates/jxl-render/src/state.rs
Try to fix occasional deadlocks.
=> jxl-render: Improve threading

crates/jxl-bitstream/src/container/parse.rs, crates/jxl-frame/src/header.rs, crates/jxl-grid/src/mutable_subgrid.rs, crates/jxl-modular/src/image.rs, crates/jxl-modular/src/predictor.rs, crates/jxl-render/src/features/noise.rs, crates/jxl-render/src/image.rs
Hot and fresh Rust 1.83.0 clippy from the oven just broke the CI...
=> Fix Rust 1.83 clippy

crates/jxl-frame/src/error.rs, crates/jxl-frame/src/lib.rs, crates/jxl-oxide/src/lib.rs
=> jxl-frame: Track group buffer allocation

CHANGELOG.md, crates/jxl-frame/src/lib.rs, crates/jxl-render/src/blend.rs
=> Fix panic in alpha blending without alpha channel

crates/jxl-image/src/lib.rs, crates/jxl-oxide-cli/src/info.rs, crates/jxl-oxide/src/aux_box.rs, crates/jxl-oxide/src/lib.rs
Print extra channel info and JPEG bitstream reconstruction availability.
=> jxl-oxide-cli: Enhance info subcommand

crates/jxl-color/src/icc/synthesize.rs
=> jxl-color: Fix cicp tag in ICC profile synthesis

.github/workflows/build.yml, .github/workflows/ci.yml, .github/workflows/coverage.yml, .github/workflows/fuzz.yml
=> Use GitHub Actions ARM runner

crates/jxl-frame/src/data/pass_group.rs, crates/jxl-grid/src/mutable_subgrid.rs, crates/jxl-grid/src/shared_subgrid.rs, crates/jxl-jbr/src/reconstruct.rs, crates/jxl-render/src/vardct/mod.rs, crates/jxl-vardct/src/hf_coeff.rs
=> Remove `AtomicI32` subgrids

crates/jxl-grid/src/test/subgrids.rs
Hi, I proposed #464 for jxl-grid before. I appended some tests for jxl-grid in this PR, thank you for taking the time to look at this PR.
=> jxl-grid: Add tests

Cargo.lock, crates/jxl-oxide-cli/Cargo.toml, crates/jxl-oxide/Cargo.toml
=> Update moxcms to 0.7.5
